# Generated by Django 5.0.2 on 2024-02-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtimeimg',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Detect_images'),
        ),
    ]
